### ISSUE TITLE
maxUploadSizeKb config not working

### ISSUE THREAD

**Issue by bangd** [linguanostra/ELFinder.Connector.NET#1]
ELFinderRootVolumeConfigEntry - maxUploadSizeKb not working in ASP.NET MVC project

**Comment by bangd** [comment]
Or It should be minUploadSizeKb?

**Comment by Hdd77** [comment]
Hello

In the function "IConnectorDriver.Upload" from the class " ELFinder.Connector.Drivers.FileSystem", the condition

            // Check if max upload size is set and that no files exceeds it            
            if (dest.Root.MaxUploadSizeKb.HasValue
                && !fileStreams.Any(x => (x.Stream.Length/1024) > dest.Root.MaxUploadSizeKb))

must be

            // Check if max upload size is set and that no files exceeds it            
            if (dest.Root.MaxUploadSizeKb.HasValue
                && fileStreams.Any(x => (x.Stream.Length/1024) > dest.Root.MaxUploadSizeKb))

and it works.

PS : sorry for my english :)

**Comment by linguanostra** [comment]
Thanks for the fix, it's working fine now. I've also updated the code.

Also, when the the MaxUploadSizeKb is set to null, there won't be any limitation.

Now, if only I could find some spare time to add some tests, that would be awesome!

Cheers!
